### ISSUE TITLE
Request limit exceeded

### ISSUE THREAD

**Issue by ken0-1n** [otiai10/awsub#10]
It can cause the request limit exceeded error when launching many EC2 instances in awsub.
Note that, This error has not yet occurred in awsub.

**Comment by ken0-1n** [comment]
This error occurred when launching about 120 EC2 instances.

    reating machine...
    (genomon-qc-tasks-ubuntu-20180209-08321022-nguwmzjl) Launching instance...
    Waiting for machine to be running, this may take a few minutes...
    Detecting operating system of created instance...
    Waiting for SSH to be available...
    Detecting the provisioner...
    Provisioning with ubuntu(systemd)...
    Installing Docker...
    Copying certs to the local machine directory...
    Copying certs to the remote machine...
    Setting Docker configuration on the remote daemon...
    Checking connection to Docker...
    Error creating machine: Error checking the host: RequestLimitExceeded: Request limit exceeded.
            status code: 503, request id: ac007d31-a800-4b71-99ef-2c0fd69d2b88

    19 task(s) failed with errors
    Process Process-4:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
        self.run()
      File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/local/lib/python2.7/dist-packages/genomon_pipeline_cloud/batch_engine.py", line 54, in execute
        subprocess.check_call(self.generate_commands(task, general_param))
      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    CalledProcessError: Command '['awsub', '--aws-iam-instance-profile', 'testtest', '--verbose', '--aws-ec2-instance-type', 't2.small', '--script', '/usr/local/lib/python2.7/dist-packages/genomon_pipeline_cloud/script/genomon-qc.sh', '--image', 'genomon/genomon_qc:latest', '--tasks', '/home/ubuntu/tools/genomon_pipeline_cloud-0.1.0/tmp/genomon-qc-tasks-ubuntu-20180209-083210.tsv']' returned non-zero exit status 1

**Comment by ken0-1n** [comment]
Good job!
 It was improved considerably by v0.0.8.
