### ISSUE TITLE
Error creating machine

### ISSUE THREAD

**Issue by aokad** [otiai10/awsub#24]
```
[paplot-task00] Creating docker machine
paplot-task00-NzhjNGI5: failed to create machine: exit status 1: Running pre-create checks...
Creating machine...
(paplot-task00-NzhjNGI5) Launching instance...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Error creating machine: Error running provisioning: Error running apt-get update: ssh command error:
command : sudo apt-get update
err     : exit status 100
output  : Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Splitting up /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_InRelease into data and signature failedErr:2 http://archive.ubuntu.com/ubuntu xenial InRelease
  Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:4 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [435 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get:6 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [189 kB]
Get:7 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [7,224 B]
Get:8 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [710 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/restricted Translation-en [2,152 B]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [200 kB]
Get:11 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [102 kB]
Get:12 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3,208 B]
Get:13 http://security.ubuntu.com/ubuntu xenial-security/multiverse Translation-en [1,408 B]
Get:14 http://archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [295 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [7,560 B]
Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/restricted Translation-en [2,272 B]
Get:17 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [579 kB]
Get:18 http://archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [234 kB]
Get:19 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [16.2 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse Translation-en [8,052 B]
Get:21 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [4,840 B]
Get:22 http://archive.ubuntu.com/ubuntu xenial-backports/main Translation-en [3,220 B]
Get:23 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [6,612 B]
Get:24 http://archive.ubuntu.com/ubuntu xenial-backports/universe Translation-en [3,768 B]
Reading package lists...
E: GPG error: http://archive.ubuntu.com/ubuntu xenial InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)

The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.


1 task(s) failed with errors
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/site-packages/genomon_pipeline_cloud/batch_engine.py", line 54, in execute
    subprocess.check_call(self.generate_commands(task, general_param))
  File "/usr/local/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['awsub', '--aws-iam-instance-profile', 'testtest', '--verbose', '--aws-ec2-instance-type', 't2.small', '--script', '/usr/local/lib/python2.7/site-packages/genomon_pipeline_cloud/script/paplot.sh', '--image', 'genomon/paplot', '--tasks', '/work/genomon_pipeline_cloud/tmp/paplot-tasks.tsv']' returned non-zero exit status 1
```

**Comment by otiai10** [comment]
- http://pages.cs.wisc.edu/~adesmet/status.html

**Comment by otiai10** [comment]
How many times did you face this problem?

**Comment by ken0-1n** [comment]
https://github.com/docker/machine/issues/3990
